const brands = [
  //   "paramountplusuk",
  //   "fiaformulae",
  //   "refinery29",
  //   "appletv",
  //   "hulu",
  //   "paramountplusuk",
  //   "sonymusicuk",
  //   "disneyuk",
  //   "warnerbrosuk",
  //   "hypebeast",
  //   "uktvplay",
  //   "lionsgateuk",
  //   "sonypicturesuk",
  //   "itvx",
  //   "picoxr",
  //   "vt",
  //   "odeoncinemas",
  //   "starmaker_officialpage",
  //   "todaytix",
  //   "discoveryplusuk",
  //   "hbo",
  //   "marvel",
  //   "disneylandparis",
  //   "global",
  //   "audible",
  //   "streamonmax",
  //   "disney",
  //   "paramountpicturesuk",
  //   "now",
  //   "soundcloud",
  //   "buzzfeeduk",
  //   "vinylboxofficial",
  //   "junglecreations",
  //   "Yousician",
  //   "national_lottery",
  //   "nationalotterygoodcauses",
  //   "theeconomist",
  //   "tate",
  //   "gaytimes",
  //   "paraympics",
  //   "glamouruk ",
  //   "vice",
  //   "peanut",
  //   "cineworld",
  //   "sixnationsrugby",
  //   "mancity",
  //   "cbbc",
  //   "emiratesfacup",
  //   "spursofficial",
  //   "highsnobiety",
  //   "goalglobal",
  //   "nbc",
  //   "lta",
  //   "peacocktvuk",
  //   "thesun",
  //   "arsenal",
  //   "disneymusic",
  //   "cymru",
  //   "paniniukofficial",
  //   "topgear",
  //   "mtvuk",
  //   "thetimes",
  //   "vue.cinemas",
  //   "multiversusgame",
  "amazon",
];

module.exports = {
  brands,
};
